name: Better-Mobs-and-Bosses
version: 1.5
author: Paul1365972

main: de.paul1365972.Main
commands:
    xpbank:
        usage: /<command>
    bmab:
        usage: /<command>
Permissions:
    bmab.enchant.blunt:
        default: false
    bmab.enchant.heavy:
        default: false
    bmab.enchant.haste:
        default: false
    bmab.enchant.frostric:
        default: false
    bmab.enchant.explode:
        default: false
    bmab.enchant.magic:
        default: false
    bmab.enchant.counter:
        default: false
    bmab.enchant.shield:
        default: false
    bmab.enchant.endering:
        default: false
    bmab.enchant.vampire:
        default: false